#cloud-config
package_update: true
package_upgrade: true

packages:
  - nginx
  - amazon-ssm-agent

runcmd:
  - [systemctl, enable, nginx]
  - [systemctl, start, nginx]
  - [systemctl, enable, amazon-ssm-agent]
  - [systemctl, start, amazon-ssm-agent]

write_files:
  - path: /usr/share/nginx/html/index.html
    content: |
      <!DOCTYPE html>
      <html>
      <head><title>React App Instance</title></head>
      <body>
        <h1>Random Nginx Page: $(date +%s%N | sha256sum | head -c 20)</h1>
        <p>Instance ID: $(curl -s http://169.254.169.254/latest/meta-data/instance-id)</p>
        <p>Launch Time: $(date)</p>
      </body>
      </html>
    owner: root:root
    permissions: '0644'
